apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-task-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang-task-manager
  template:
    metadata:
      labels:
        app: golang-task-manager
    spec:
      containers:
      - name: golang-task-manager
        image: 7usman/golang-task-manager:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "postgres"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "7usmann"
        - name: DB_NAME
          value: "task_manager"
---
apiVersion: v1
kind: Service
metadata:
  name: golang-task-manager
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: golang-task-manager
